### ISSUE TITLE
Formatter: indents became bigger

### ISSUE THREAD

**Issue by annstriganova** [axibase/charts-language-service#64]
It seems that there is `\t` instead of `\s{2}`.
![Selection_001](https://user-images.githubusercontent.com/20650874/64691369-307c9080-d49b-11e9-9044-b0d26249d1ae.png)

**Comment by PolinaShneider** [comment]
How to reproduce? Is it chartlab or local charts-editor sandbox?

**Comment by annstriganova** [comment]
https://apps.axibase.com/chartlab/17fba87d/3/

**Comment by PolinaShneider** [comment]
Tried to investigate the problem. Probably, this bug isn't related to language-service and has something to do with monaco. 

Tests in `charts-language-service` are OK. VSCode plugin with latest version of language service is okay too. Will hope that this issue will resolve when [this](https://github.com/axibase/charts-language-service/pull/46) PR is merged, because bug isn't reproduced locally either.

**Comment by PolinaShneider** [comment]
Definitely it isn't a problem with `charts-language-service`. Probably, `monaco-editor` is adjusting indents automatically. 

I have set `tabSize = 2` by default. Also added possibility to configure tabSize manually. For example in chartlab call API method: 

```
ChartsEditor.editorActions.setTabSize(4) // tabSize = 4
```

@annstriganova check if problem is fixed for you, and close the issue then.

**Comment by annstriganova** [comment]
For future reference: https://github.com/axibase/charts-editor/pull/30
Works as expected.
