### ISSUE TITLE
False start-time and end-time errors 

### ISSUE THREAD

**Issue by rodionos** [axibase/charts-language-service#8]
https://apps.axibase.com/chartlab/e3f9dfe6/8/

The settings are valid but an error is highlighted. The error message is not visible.

```
  #timespan = 180 minute
  start-time = 2019-08-14T10:00:00Z
  end-time =   2019-08-14T16:00:00Z
  update-interval = 0 second
```

**Comment by annstriganova** [comment]
Could you provide more info, how can I detect the problem?
![Selection_001](https://user-images.githubusercontent.com/20650874/63092231-b58e8b80-bf69-11e9-9916-745f551d65f7.png)

**Comment by annstriganova** [comment]
The reason, why it works in Chrome and doesn't work in FF, is the following:

![Selection_002](https://user-images.githubusercontent.com/20650874/63094717-d8bd3900-bf71-11e9-8591-a92bd5cffd19.png)

![Selection_002](https://user-images.githubusercontent.com/20650874/63094783-f9858e80-bf71-11e9-99b8-c54a0322064b.png)

That is, the problem is in the lower case.
